"""``githooks doctor``: explain why the hooks do (or do not) run in a repository.

Each finding is ✓ ok, · info, ! warning or ✗ error; the exit code is 1 when
there is at least one error. It checks:

- the config: both parsers can read it and agree, no unknown checks, stages,
  sections or settings (with "did you mean"), value types, regexes, modes;
- a native install: core.hooksPath, one working wrapper per stage in use, the
  interpreter those wrappers actually resolve (by running one in probe mode),
  and drift between the vendored copy and this version;
- a pre-commit framework install: every hook type the configured hooks need
  is installed, and the pinned rev is not a tag that never existed;
- known-bad combinations (issue prefix vs. Conventional Commits) and which
  formatter / linter each language in the repository will get.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
from copy import deepcopy
from pathlib import Path

from . import __version__, _core, _miniyaml, config_schema, installer, registry
from .conventional_commit import validate as validate_message
from .format_code import _first_available_tool

FRAMEWORK_MARKER = "File generated by pre-commit"


class Report:
    def __init__(self) -> None:
        self.errors = 0
        self.warnings = 0

    def _line(self, glyph: str, colour: str, msg: str) -> None:
        print(f"{colour}{glyph}{_core.C.RESET} {msg}")

    def ok(self, msg: str) -> None:
        self._line("✓", _core.C.GREEN, msg)

    def info(self, msg: str) -> None:
        self._line("·", _core.C.CYAN, msg)

    def warn(self, msg: str) -> None:
        self.warnings += 1
        self._line("!", _core.C.YELLOW, msg)

    def error(self, msg: str) -> None:
        self.errors += 1
        self._line("✗", _core.C.RED, msg)

    def section(self, title: str) -> None:
        print(f"\n{_core.C.BOLD}{title}{_core.C.RESET}")


# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #
def check_config(r: Report, root: Path) -> dict:
    r.section("Configuration")
    path = _core.find_config_file()
    if path is None:
        r.info("no .githooks.yaml: the shipped defaults apply")
        return deepcopy(_core.DEFAULTS)
    r.info(f"config file: {path}")
    text = path.read_text(encoding="utf-8")
    try:
        mini = _miniyaml.safe_load(text)
    except Exception as exc:  # noqa: BLE001 - report any parse failure
        r.error(f"the bundled parser cannot read it: {exc}")
        mini = None
    data = mini
    try:
        import yaml  # type: ignore[import-untyped]
    except ImportError:
        r.info("PyYAML is not installed; the hooks use the bundled parser")
    else:
        try:
            pyyaml = yaml.safe_load(text)
        except Exception as exc:  # noqa: BLE001
            r.error(f"PyYAML cannot read it: {exc}")
        else:
            if mini is not None:
                diff = config_schema.first_difference(pyyaml, mini)
                if diff:
                    where, a, b = diff
                    r.error(
                        f"PyYAML and the bundled parser disagree at {where or '<root>'}: "
                        f"{a!r} vs {b!r}. Quote the value so every machine reads the same."
                    )
                else:
                    r.ok("PyYAML and the bundled parser read it identically")
            data = pyyaml if data is None else data
    if data is None:
        return deepcopy(_core.DEFAULTS)
    problems = config_schema.validate(data, _core.DEFAULTS)
    for problem in problems:
        (r.error if problem.level == config_schema.ERROR else r.warn)(str(problem))
    if not problems:
        r.ok("every section, setting and check name is known")
    merged = _core._deep_merge(_core.DEFAULTS, data) if isinstance(data, dict) else _core.DEFAULTS
    return merged


def enabled_by_stage(config: dict) -> dict[str, list[str]]:
    return {
        stage: [str(n) for n in _core.cfg_list(config, f"hooks.{stage}") if registry.get(str(n))]
        for stage in registry.STAGES
    }


# --------------------------------------------------------------------------- #
# Native install
# --------------------------------------------------------------------------- #
def _probe(sh: str, wrapper: Path, root: Path) -> dict | None:
    env = dict(os.environ, GITHOOKS_PROBE="1")
    try:
        proc = subprocess.run(
            [sh, str(wrapper)],
            cwd=str(root),
            env=env,
            capture_output=True,
            encoding="utf-8",
            errors="replace",
            timeout=60,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"error": str(exc)}
    try:
        return json.loads(proc.stdout.strip().splitlines()[-1])
    except (IndexError, ValueError):
        return {"error": (proc.stdout + proc.stderr).strip() or f"exit code {proc.returncode}"}


def _digest(path: Path) -> str:
    return hashlib.sha1(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def _drift(vendored: Path) -> list[str]:
    source = installer.PACKAGE_DIR
    if vendored.resolve() == source.resolve():
        return []
    differing = []
    for src in sorted(source.rglob("*")):
        if not src.is_file() or "__pycache__" in src.parts or src.suffix in (".pyc", ".pyo"):
            continue
        rel = src.relative_to(source)
        dst = vendored / rel
        if not dst.is_file() or _digest(dst) != _digest(src):
            differing.append(rel.as_posix())
    return differing


def _vendored_version(vendored: Path) -> str | None:
    init = vendored / "__init__.py"
    if not init.is_file():
        return None
    m = re.search(r'__version__\s*=\s*["\']([^"\']+)', init.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def check_native(r: Report, root: Path, enabled: dict[str, list[str]]) -> None:
    r.section("Native install (.githooks/)")
    hooks_dir = root / installer.HOOKS_DIR
    current, origin = installer.hooks_path_setting(root)
    if installer.is_our_hooks_path(current, root):
        r.ok(f"core.hooksPath = {current} ({origin})")
    elif current:
        r.error(
            f"core.hooksPath points at '{current}' ({origin}), so the hooks in .githooks/ never "
            "run. Fix: git config core.hooksPath .githooks"
        )
    else:
        r.error(
            "core.hooksPath is not set, so the hooks in .githooks/ never run. "
            "Fix: git config core.hooksPath .githooks"
        )

    active = [s for s in registry.STAGES if enabled.get(s)]
    for stage in registry.STAGES:
        wrapper = hooks_dir / stage
        if stage not in active:
            if wrapper.is_file():
                r.info(f"{stage}: wrapper present but no checks enabled (harmless)")
            continue
        checks = ", ".join(enabled[stage])
        if not wrapper.is_file():
            r.error(
                f"{stage}: {checks} enabled, but .githooks/{stage} is missing, so they never run. "
                "Fix: githooks install"
            )
            continue
        raw = wrapper.read_bytes()
        if not raw.startswith(b"#!"):
            r.error(f"{stage}: .githooks/{stage} has no #! line; git will not run it")
        elif b"\r\n" in raw:
            r.error(f"{stage}: .githooks/{stage} has CRLF line endings; sh on Linux/macOS fails")
        elif os.name != "nt" and not os.access(wrapper, os.X_OK):
            r.error(
                f"{stage}: .githooks/{stage} is not executable. Fix: chmod +x .githooks/{stage}"
            )
        elif installer.WRAPPER_TAG.encode() not in raw:
            r.warn(f"{stage}: .githooks/{stage} is a custom hook, not this project's wrapper")
        else:
            r.ok(f"{stage}: wrapper runs {checks}")

    sh = _core.find_sh()
    probe_target = next((hooks_dir / s for s in active if (hooks_dir / s).is_file()), None)
    if probe_target is not None and sh:
        result = _probe(sh, probe_target, root)
        if result and "python" in result:
            version = ".".join(str(v) for v in result.get("version", []))
            r.ok(
                f"the wrappers run {result['python']} (Python {version}) with "
                f"git-hooks-collection {result.get('package_version')}"
            )
            if tuple(result.get("version", [0])) < (3, 8):
                r.error("the hooks need Python 3.8 or newer; set GITHOOKS_PYTHON")
        else:
            r.error(
                f"running .githooks/{probe_target.name} failed: {result and result.get('error')}"
            )
    elif probe_target is not None:
        r.warn("no POSIX sh found to test-run a wrapper")

    vendored = hooks_dir / "pre_commit_hooks"
    version = _vendored_version(vendored)
    if version is None:
        r.error("the vendored package .githooks/pre_commit_hooks is missing. Fix: githooks install")
    else:
        differing = _drift(vendored)
        if version != __version__:
            r.warn(
                f"vendored copy is {version}, this is {__version__}; "
                "`githooks install` refreshes it and keeps your config"
            )
        elif differing:
            r.warn(
                f"vendored copy differs from {__version__} in {len(differing)} file(s) "
                f"({', '.join(differing[:3])}{'...' if len(differing) > 3 else ''})"
            )
        else:
            r.ok(f"vendored copy matches git-hooks-collection {__version__}")

    if installer.is_our_hooks_path(current, root):
        bypassed = installer.bypassed_hooks(root)
        if bypassed:
            r.warn(
                f"hooks in .git/hooks are ignored while core.hooksPath is set: {', '.join(bypassed)}"
            )


# --------------------------------------------------------------------------- #
# pre-commit framework install
# --------------------------------------------------------------------------- #
_ID_RX = re.compile(r"^\s*-?\s*id:\s*['\"]?(githooks-[a-z-]+)", re.MULTILINE)
_REV_RX = re.compile(r"^\s*rev:\s*['\"]?([^\s'\"#]+)", re.MULTILINE)


def framework_hook_ids(root: Path) -> list[str]:
    cfg = root / ".pre-commit-config.yaml"
    if not cfg.is_file():
        return []
    return list(dict.fromkeys(_ID_RX.findall(cfg.read_text(encoding="utf-8"))))


def check_framework(r: Report, root: Path, ids: list[str]) -> dict[str, list[str]]:
    r.section("pre-commit framework (.pre-commit-config.yaml)")
    by_id = {c.hook_id: c for c in registry.CHECKS}
    enabled: dict[str, list[str]] = {s: [] for s in registry.STAGES}
    for hook_id in ids:
        check = by_id.get(hook_id)
        if check is None:
            hint = registry.suggest(hook_id, list(by_id))
            r.error(f"unknown hook id '{hook_id}'" + (f" (did you mean '{hint}'?)" if hint else ""))
            continue
        enabled[check.stage].append(check.name)
    current, origin = installer.hooks_path_setting(root)
    if current:
        r.error(
            f"core.hooksPath is set to '{current}' ({origin}); pre-commit refuses to install "
            "while it is set, and git ignores .git/hooks"
        )
    hooks = installer.default_hooks_dir(root)
    for stage, names in enabled.items():
        if not names:
            continue
        script = hooks / stage
        installed = script.is_file() and FRAMEWORK_MARKER in script.read_text(
            encoding="utf-8", errors="ignore"
        )
        if installed:
            r.ok(f"{stage}: pre-commit hook installed ({', '.join(names)})")
        else:
            r.error(
                f"{stage}: {', '.join(names)} configured, but the {stage} hook type is not "
                f"installed. Fix: pre-commit install --hook-type {stage}"
            )
    for rev in _REV_RX.findall((root / ".pre-commit-config.yaml").read_text(encoding="utf-8")):
        if rev == "v0.1.0":
            r.error(
                "rev v0.1.0 was never released (the 0.1.0 docs pinned a tag that does not "
                "exist). Pin a commit SHA, or run `pre-commit autoupdate` once a tag exists"
            )
    return enabled


# --------------------------------------------------------------------------- #
# Behaviour
# --------------------------------------------------------------------------- #
def tracked_languages(exclude: list[str] | None = None) -> dict[str, int]:
    counts: dict[str, int] = {}
    for path in _core.index_entries():
        if exclude and _core.path_excluded(path, exclude):
            continue
        lang = _core.language_of(path)
        if lang:
            counts[lang] = counts.get(lang, 0) + 1
    return counts


def check_behaviour(r: Report, config: dict, enabled: dict[str, list[str]]) -> None:
    r.section("Behaviour")
    names = {n for stage in enabled.values() for n in stage}
    if not names:
        r.warn("no checks are enabled")
        return
    r.info("checks in use: " + ", ".join(n for n in registry.NAMES if n in names))
    if "issue-prefix" in names and "conventional-commit" in names:
        mode = str(_core.cfg(config, "issue_prefix.mode", "trailer")).lower()
        if mode == "prefix":
            template = str(_core.cfg(config, "issue_prefix.template", "[{issue}] "))
            sample = template.replace("{issue}", "ABC-123") + "feat: add a thing"
            errors = validate_message(sample, config)
            if errors:
                r.error(
                    f"issue_prefix.mode: prefix turns 'feat: add a thing' into {sample!r}, which "
                    f"conventional-commit rejects ({errors[0]}). Use mode: trailer, or make "
                    "conventional_commit.ignore_prefix_regex match the prefix"
                )
            else:
                r.ok("issue-prefix (prefix mode) and conventional-commit work together")
        else:
            r.ok("issue-prefix adds a Refs: trailer, which conventional-commit accepts")

    for check in ("format", "lint"):
        if check not in names:
            continue
        languages = tracked_languages([str(p) for p in _core.cfg_list(config, f"{check}.exclude")])
        tools = _core.cfg(config, f"{check}.tools", {}) or {}
        for lang, count in sorted(languages.items()):
            specs = tools.get(lang) or []
            specs = [specs] if isinstance(specs, str) else list(specs)
            if not specs:
                continue
            tool = _first_available_tool(specs)
            if tool:
                r.ok(f"{check}: {lang} ({count} files) -> {_core.tool_name(tool[0])}")
            else:
                r.warn(
                    f"{check}: none of {', '.join(map(str, specs))} is installed, so {count} "
                    f"{lang} file(s) are not {'formatted' if check == 'format' else 'linted'}"
                )
    if "tests" in names:
        from .run_tests import _detect_command

        command = _detect_command(config)
        if command:
            r.ok(f"tests: pre-push runs `{' '.join(command)}`")
        else:
            r.info("tests: no test command configured or detected; the check passes quietly")


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #
def run(target: str = ".") -> int:
    root = installer.git_root(Path(target).resolve())
    if root is None:
        print(f"✗ {target} is not inside a git repository", file=sys.stderr)
        return 2
    os.chdir(root)
    r = Report()
    print(f"{_core.C.BOLD}git-hooks-collection {__version__} doctor{_core.C.RESET}: {root}")
    config = check_config(r, root)

    native = (root / installer.HOOKS_DIR / installer.MARKER).is_file()
    ids = framework_hook_ids(root)
    if native:
        enabled = enabled_by_stage(config)
        check_native(r, root, enabled)
    elif ids:
        enabled = check_framework(r, root, ids)
    else:
        r.section("Installation")
        r.error(
            "git-hooks-collection is not installed here (no .githooks/ and no githooks-* ids in "
            ".pre-commit-config.yaml). Fix: githooks install"
        )
        enabled = enabled_by_stage(config)
    check_behaviour(r, config, enabled)

    verdict = (
        "no problems found"
        if not (r.errors or r.warnings)
        else (f"{r.errors} error(s), {r.warnings} warning(s)")
    )
    print(f"\n{_core.C.BOLD}doctor:{_core.C.RESET} {verdict}")
    return 1 if r.errors else 0
