"""Install the hooks into a repository (``install.py`` and ``githooks install``).

Two delivery paths:

native (default)
    Vendors this package into ``<repo>/.githooks/``, writes one small shell
    wrapper per git stage that has checks enabled, writes ``.githooks.yaml``
    (unless one exists) and points ``core.hooksPath`` at ``.githooks``. The
    directory is meant to be committed so the whole team shares the hooks with
    no pip install.

pre-commit
    Writes (or prints) a ``.pre-commit-config.yaml`` block that references this
    project, pinned to a revision that actually exists: the source checkout's
    exact tag if there is one, otherwise its commit SHA.

Re-running the installer is safe and idempotent. An explicit selection
(``--hooks`` / ``--all``) rewrites only the ``hooks:`` block of an existing
``.githooks.yaml`` and keeps every threshold; wrappers for stages that no longer
have checks are removed. An existing ``core.hooksPath`` that points somewhere
else (husky, lefthook, a global hooks directory) is never silently replaced.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from . import __version__, _core, registry

PACKAGE_DIR = Path(__file__).resolve().parent
SOURCE_DIR = PACKAGE_DIR.parent  # the checkout root when running from source
TEMPLATE_PATH = _core.TEMPLATE_PATH
REPO_URL = "https://github.com/AleBrito124356/git-hooks-collection"
MARKER = ".githooks-collection"
WRAPPER_TAG = "Auto-generated by git-hooks-collection"
HOOKS_DIR = ".githooks"

STAGE_ORDER = list(registry.STAGES)
ALL_NAMES = list(registry.NAMES)
NAME_TO_STAGE = {c.name: c.stage for c in registry.CHECKS}
NAME_TO_ID = {c.name: c.hook_id for c in registry.CHECKS}

# Exit codes.
EXIT_OK = 0
EXIT_FAIL = 1
EXIT_USAGE = 2
EXIT_FOREIGN_HOOKS_PATH = 3

# Never let a status glyph or a non-ASCII file name crash a hook on a legacy
# (cp1252) console: degrade unencodable characters instead of raising. On
# Windows, a stream that is a pipe rather than a console (Git Bash / mintty,
# IDE terminals) expects UTF-8, so write UTF-8 there instead of cp1252.
for _stream in (sys.stdout, sys.stderr):
    try:
        if os.name == "nt" and not _stream.isatty():  # type: ignore[union-attr]
            _stream.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
        else:
            _stream.reconfigure(errors="replace")  # type: ignore[union-attr]
    except (AttributeError, ValueError, OSError):  # not every stream supports it
        pass


# --------------------------------------------------------------------------- #
# Output (stdout: this is an interactive tool, not a hook)
# --------------------------------------------------------------------------- #
def _c(code: str, text: str) -> str:
    if os.environ.get("NO_COLOR") or not sys.stdout.isatty():
        return text
    return f"\033[{code}m{text}\033[0m"


def info(msg: str) -> None:
    print(_c("36", "· ") + msg)


def ok(msg: str) -> None:
    print(_c("32", "✓ ") + msg)


def warn(msg: str) -> None:
    print(_c("33", "! ") + msg)


def fail(msg: str) -> None:
    print(_c("31", "✗ ") + msg, file=sys.stderr)


# --------------------------------------------------------------------------- #
# Git helpers
# --------------------------------------------------------------------------- #
def _git(root: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        encoding="utf-8",
        errors="replace",
        check=False,
    )


def git_root(target: Path) -> Optional[Path]:
    proc = _git(target, "rev-parse", "--show-toplevel")
    if proc.returncode != 0 or not proc.stdout.strip():
        return None
    return Path(proc.stdout.strip())


def git_config(root: Path, *args: str) -> subprocess.CompletedProcess:
    return _git(root, "config", *args)


def hooks_path_setting(root: Path) -> Tuple[Optional[str], str]:
    """The effective core.hooksPath (any scope) and where it is set."""
    proc = git_config(root, "--show-origin", "--get", "core.hooksPath")
    if proc.returncode != 0 or not proc.stdout.strip():
        return None, ""
    origin, _, value = proc.stdout.strip().partition("\t")
    return value.strip(), origin


def is_our_hooks_path(value: Optional[str], root: Path) -> bool:
    if not value:
        return False
    norm = value.replace("\\", "/").rstrip("/")
    if norm in (HOOKS_DIR, f"./{HOOKS_DIR}"):
        return True
    try:
        return Path(value).expanduser().resolve() == (root / HOOKS_DIR).resolve()
    except OSError:
        return False


def default_hooks_dir(root: Path) -> Path:
    """.git/hooks for this repository (worktree aware)."""
    proc = _git(root, "rev-parse", "--git-common-dir")
    common = Path(proc.stdout.strip() or ".git")
    if not common.is_absolute():
        common = root / common
    return common / "hooks"


def bypassed_hooks(root: Path) -> List[str]:
    """Active hooks in .git/hooks that stop running once core.hooksPath is set."""
    hooks = default_hooks_dir(root)
    if not hooks.is_dir():
        return []
    names = []
    for entry in sorted(hooks.iterdir()):
        if entry.is_file() and not entry.name.endswith(".sample"):
            names.append(entry.name)
    return names


# --------------------------------------------------------------------------- #
# Config rendering
# --------------------------------------------------------------------------- #
_HOOKS_KEY_RX = re.compile(r"^hooks:\s*(#.*)?$")
_TOP_LEVEL_RX = re.compile(r"^[^\s#]")


def hooks_block(selected: List[str]) -> str:
    """The ``hooks:`` section for a selection, in stage and catalogue order."""
    lines = ["hooks:"]
    for stage in STAGE_ORDER:
        names = [n for n in ALL_NAMES if n in selected and NAME_TO_STAGE[n] == stage]
        if names:
            lines.append(f"  {stage}:")
            lines.extend(f"    - {n}" for n in names)
        else:
            lines.append(f"  {stage}: []")
    return "\n".join(lines) + "\n"


def replace_hooks_block(text: str, selected: List[str]) -> str:
    """Swap the top-level ``hooks:`` section of a config, keeping everything else.

    Comments and thresholds in the rest of the file are preserved byte for byte.
    """
    lines = text.splitlines(keepends=True)
    start = next((i for i, line in enumerate(lines) if _HOOKS_KEY_RX.match(line)), None)
    block = hooks_block(selected)
    if start is None:
        insert_at = next(
            (i + 1 for i, line in enumerate(lines) if line.startswith("version:")), 0
        )
        prefix = "".join(lines[:insert_at])
        sep = "\n" if prefix and not prefix.endswith("\n\n") else ""
        return prefix + sep + block + "\n" + "".join(lines[insert_at:])
    end = start + 1
    while end < len(lines) and not _TOP_LEVEL_RX.match(lines[end]):
        end += 1
    # Blank lines and column-0 comments just above the next key belong to it.
    while end > start + 1 and (not lines[end - 1].strip() or lines[end - 1].startswith("#")):
        end -= 1
    return "".join(lines[:start]) + block + "".join(lines[end:])


def render_config(selected: Optional[List[str]] = None) -> str:
    """The shipped template, with the hooks block narrowed to ``selected``."""
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    if selected is None or set(selected) == set(ALL_NAMES):
        return template
    return replace_hooks_block(template, selected)


# Backwards-compatible name used by earlier versions of install.py.
_render_config = render_config


def enabled_checks(config_path: Path) -> Dict[str, List[str]]:
    """stage -> check names, as the hooks will read the config file."""
    config = _core.DEFAULTS
    if config_path.is_file():
        data = _core.parse_yaml(config_path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            config = _core._deep_merge(_core.DEFAULTS, data)
    return {stage: [str(n) for n in _core.cfg_list(config, f"hooks.{stage}")] for stage in STAGE_ORDER}


def wrapper_script(stage: str) -> str:
    return (
        "#!/usr/bin/env sh\n"
        f"# {WRAPPER_TAG} for the {stage} stage.\n"
        "# Delegates to the bundled dispatcher; edit .githooks.yaml to change behaviour.\n"
        'here="$(cd "$(dirname "$0")" && pwd)"\n'
        "# $GITHOOKS_PYTHON wins; Windows App Execution Alias stubs are a last resort.\n"
        'PY="${GITHOOKS_PYTHON:-}"\n'
        'if [ -z "$PY" ]; then\n'
        '  fallback=""\n'
        "  for cand in python3 python; do\n"
        '    found="$(command -v "$cand" 2>/dev/null)" || continue\n'
        '    case "$found" in\n'
        '      *WindowsApps*) [ -n "$fallback" ] || fallback="$found" ;;\n'
        '      *) PY="$found"; break ;;\n'
        "    esac\n"
        "  done\n"
        '  [ -n "$PY" ] || PY="$fallback"\n'
        "fi\n"
        'if [ -z "$PY" ]; then\n'
        '  echo "git-hooks-collection: python not found on PATH (set GITHOOKS_PYTHON)" >&2\n'
        "  exit 1\n"
        "fi\n"
        f'exec "$PY" "$here/githooks-run.py" {stage} "$@"\n'
    )


_wrapper_script = wrapper_script  # backwards-compatible name

RUNNER_SCRIPT = '''#!/usr/bin/env python3
"""{tag}: entry point the stage wrappers call."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from pre_commit_hooks.dispatch import main  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(main())
'''.format(tag=WRAPPER_TAG)


def _write(path: Path, text: str, executable: bool = False) -> None:
    # Always LF: a CRLF wrapper breaks POSIX sh for teammates on Linux/macOS.
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    if executable:
        try:
            path.chmod(0o755)
        except OSError:
            pass


# --------------------------------------------------------------------------- #
# Native install
# --------------------------------------------------------------------------- #
def vendor_package(hooks_dir: Path) -> None:
    pkg_dst = hooks_dir / "pre_commit_hooks"
    # Running from the vendored copy itself (python .githooks/githooks-run.py
    # install): it is already in place, and deleting it would delete ourselves.
    if pkg_dst.resolve() != PACKAGE_DIR.resolve():
        if pkg_dst.exists():
            shutil.rmtree(pkg_dst)
        shutil.copytree(
            PACKAGE_DIR,
            pkg_dst,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
        )
    _write(hooks_dir / "githooks-run.py", RUNNER_SCRIPT, executable=True)
    _write(hooks_dir / ".gitignore", "__pycache__/\n*.py[cod]\n")
    _write(hooks_dir / ".gitattributes", "* text=auto eol=lf\n")
    _write(
        hooks_dir / MARKER,
        f"Managed by git-hooks-collection {__version__} (install.py / githooks install).\n"
        "Safe to commit. Re-run the installer to update it.\n",
    )


def install_native(root: Path, selected: Optional[List[str]], force: bool = False) -> int:
    """Install into ``root``. ``selected=None`` keeps an existing config's selection."""
    current, origin = hooks_path_setting(root)
    if current and not is_our_hooks_path(current, root):
        if not force:
            fail(f"core.hooksPath is already set to '{current}' ({origin}).")
            fail(
                "Another hook manager (husky, lefthook, a global hooks directory ...) runs "
                "this repository's hooks; installing would silently switch it off."
            )
            print(
                "  Re-run with --force to take over core.hooksPath, or use the pre-commit\n"
                "  framework path instead: --mode pre-commit",
                file=sys.stderr,
            )
            return EXIT_FOREIGN_HOOKS_PATH
        warn(f"replacing core.hooksPath '{current}' ({origin}) because of --force")
    if not is_our_hooks_path(current, root):
        bypassed = bypassed_hooks(root)
        if bypassed:
            warn(
                "these hooks in .git/hooks stop running once core.hooksPath points at "
                f".githooks: {', '.join(bypassed)}"
            )
            if any("lfs" in (default_hooks_dir(root) / n).read_text(errors="ignore") for n in bypassed):
                warn("  they include git-lfs hooks: without them LFS objects are not pushed.")

    hooks_dir = root / HOOKS_DIR
    hooks_dir.mkdir(parents=True, exist_ok=True)
    vendor_package(hooks_dir)

    config_path = root / ".githooks.yaml"
    if not config_path.exists():
        _write(config_path, render_config(selected))
        ok(f"wrote {config_path.name}")
    elif selected is not None:
        original = config_path.read_text(encoding="utf-8")
        updated = replace_hooks_block(original, selected)
        if updated != original:
            _write(config_path, updated)
            ok(f"updated the hooks: block of {config_path.name} (all other settings kept)")
        else:
            info(f"{config_path.name} already enables exactly these checks")
    else:
        info(f"keeping existing {config_path.name} (pass --hooks or --all to change the selection)")

    try:
        enabled = enabled_checks(config_path)
    except Exception as exc:  # noqa: BLE001 - report config errors, do not crash
        fail(f"cannot parse {config_path.name}: {exc}")
        return EXIT_FAIL
    active_stages = [s for s in STAGE_ORDER if enabled.get(s)]
    for stage in active_stages:
        _write(hooks_dir / stage, wrapper_script(stage), executable=True)
    removed = []
    for stage in STAGE_ORDER:
        path = hooks_dir / stage
        if stage not in active_stages and path.is_file():
            if WRAPPER_TAG in path.read_text(encoding="utf-8", errors="ignore"):
                path.unlink()
                removed.append(stage)

    result = git_config(root, "core.hooksPath", HOOKS_DIR)
    if result.returncode != 0:
        fail(f"could not set core.hooksPath: {result.stderr.strip()}")
        return EXIT_FAIL

    total = sum(len(v) for v in enabled.values())
    ok(f"installed {total} check(s) into {HOOKS_DIR}/ and set core.hooksPath")
    if removed:
        info(f"removed wrappers for stages with no checks left: {', '.join(removed)}")
    print()
    info("Enabled checks:")
    for stage in STAGE_ORDER:
        for name in enabled.get(stage, []):
            print(f"    {name:<22} ({stage})")
    print()
    info("Commit the .githooks/ directory so your whole team gets these hooks:")
    print("    git add .githooks .githooks.yaml")
    print('    git commit -m "chore: add shared git hooks"')
    print()
    info("Teammates activate them with a single command after cloning:")
    print("    git config core.hooksPath .githooks")
    return EXIT_OK


# --------------------------------------------------------------------------- #
# pre-commit framework install
# --------------------------------------------------------------------------- #
def resolve_rev(source: Path = SOURCE_DIR) -> Tuple[str, str, List[str]]:
    """(rev, explanation, warnings) to pin in a .pre-commit-config.yaml.

    Only revisions that exist are offered: the exact tag at the source
    checkout's HEAD, else the HEAD commit SHA. A pip-installed copy has no git
    metadata; then the version tag is used and flagged as unverified.
    """
    warnings: List[str] = []
    is_checkout = (source / ".pre-commit-hooks.yaml").is_file()
    top = git_root(source) if is_checkout else None
    if top is not None and top.resolve() == source.resolve():
        tag = _git(source, "describe", "--tags", "--exact-match", "HEAD")
        if tag.returncode == 0 and tag.stdout.strip():
            name = tag.stdout.strip()
            return name, f"tag {name}, which points at the source checkout's HEAD", warnings
        sha = _git(source, "rev-parse", "HEAD").stdout.strip()
        if sha:
            remote = _git(source, "branch", "-r", "--contains", "HEAD")
            if remote.returncode == 0 and not remote.stdout.strip():
                warnings.append(
                    f"{sha[:12]} is not on any remote branch yet: pre-commit cannot fetch it "
                    "until it is pushed"
                )
            dirty = _git(source, "status", "--porcelain", "--untracked-files=no")
            if dirty.stdout.strip():
                warnings.append("the source checkout has uncommitted changes; they are not in this rev")
            return sha, "commit SHA of the source checkout (no release tag points at HEAD)", warnings
    rev = f"v{__version__}"
    warnings.append(
        f"could not verify that {rev} exists (not running from a git checkout); "
        "check with `git ls-remote --tags` or run `pre-commit autoupdate`"
    )
    return rev, "package version tag (unverified)", warnings


def pre_commit_snippet(selected: List[str], rev: str, repo_url: str = REPO_URL) -> str:
    hook_lines = "\n".join(f"      - id: {NAME_TO_ID[n]}" for n in selected)
    return f"repos:\n  - repo: {repo_url}\n    rev: {rev}\n    hooks:\n{hook_lines}\n"


# Backwards-compatible name.
def _pre_commit_snippet(selected: List[str]) -> str:
    return pre_commit_snippet(selected, resolve_rev()[0])


def install_pre_commit(
    root: Path,
    selected: List[str],
    rev: Optional[str] = None,
    repo_url: str = REPO_URL,
) -> int:
    if rev:
        explanation, warnings = "given with --rev", []
    else:
        rev, explanation, warnings = resolve_rev()
    config_path = root / ".pre-commit-config.yaml"
    snippet = pre_commit_snippet(selected, rev, repo_url)
    info(f"pinning rev: {rev} ({explanation})")
    for message in warnings:
        warn(message)
    if config_path.exists():
        warn(f"{config_path.name} already exists; not overwriting it.")
        print("\nAdd this block under its 'repos:' key:\n")
        print("\n".join(snippet.splitlines()[1:]))
    else:
        _write(config_path, snippet)
        ok(f"wrote {config_path.name}")

    stages = [s for s in STAGE_ORDER if any(NAME_TO_STAGE[n] == s for n in selected)]
    print()
    info("Then install the framework hooks for every stage these use:")
    print("    pipx install pre-commit   # or: pip install pre-commit")
    print("    pre-commit install " + " ".join(f"--hook-type {s}" for s in stages))
    print()
    info("Once a release tag exists, `pre-commit autoupdate` moves the pin to it.")
    return EXIT_OK


# --------------------------------------------------------------------------- #
# Uninstall
# --------------------------------------------------------------------------- #
def uninstall(root: Path) -> int:
    current, _origin = hooks_path_setting(root)
    local = git_config(root, "--local", "--get", "core.hooksPath")
    if local.returncode == 0 and is_our_hooks_path(local.stdout.strip(), root):
        git_config(root, "--local", "--unset", "core.hooksPath")
        ok("unset core.hooksPath")
    elif current:
        info(f"core.hooksPath is '{current}', not this installer's; leaving git config alone")
    else:
        info("core.hooksPath was not set; leaving git config alone")

    hooks_dir = root / HOOKS_DIR
    if (hooks_dir / MARKER).is_file():
        shutil.rmtree(hooks_dir)
        ok("removed .githooks/ (generated by this installer)")
    else:
        info("no installer-managed .githooks/ directory to remove")

    info("Left .githooks.yaml in place. Delete it manually if you no longer want it.")
    info("Using the pre-commit framework instead? Run: pre-commit uninstall")
    return EXIT_OK


# --------------------------------------------------------------------------- #
# Selection
# --------------------------------------------------------------------------- #
def choose_interactively() -> List[str]:
    print("Available hooks (all enabled by default):\n")
    for idx, check in enumerate(registry.CHECKS, start=1):
        print(f"  {idx:>2}. {check.name:<22} {_c('2', check.stage):<28} {check.description}")
    print()
    raw = input("Numbers to DISABLE (comma-separated), or press Enter to keep all: ").strip()
    if not raw:
        return list(ALL_NAMES)
    disabled = set()
    for part in raw.replace(" ", "").split(","):
        if not part:
            continue
        try:
            disabled.add(int(part))
        except ValueError:
            warn(f"ignoring '{part}' (not a number)")
    return [name for i, name in enumerate(ALL_NAMES, start=1) if i not in disabled]


def parse_hooks_arg(raw: str) -> List[str]:
    requested = [h.strip() for h in raw.split(",") if h.strip()]
    unknown = [h for h in requested if h not in ALL_NAMES]
    if unknown:
        for name in unknown:
            hint = registry.suggest(name)
            fail(f"unknown hook '{name}'" + (f" (did you mean '{hint}'?)" if hint else ""))
        fail(f"valid names: {', '.join(ALL_NAMES)}")
        raise SystemExit(EXIT_USAGE)
    return requested


def resolve_selection(args: argparse.Namespace, config_exists: bool) -> Optional[List[str]]:
    """The checks to enable, or None to keep an existing config's selection."""
    if args.hooks:
        return parse_hooks_arg(args.hooks)
    if args.all:
        return list(ALL_NAMES)
    if config_exists:
        return None
    if args.yes or not sys.stdin.isatty():
        return list(ALL_NAMES)
    return choose_interactively()


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #
def add_install_arguments(p: argparse.ArgumentParser) -> None:
    p.add_argument(
        "--mode",
        choices=["native", "pre-commit"],
        default="native",
        help="native installer (default) or generate a .pre-commit-config.yaml",
    )
    p.add_argument("--all", action="store_true", help="enable every hook without prompting")
    p.add_argument("--hooks", help="comma-separated hook names to enable")
    p.add_argument("--yes", action="store_true", help="assume yes / accept defaults")
    p.add_argument("--target", default=".", help="path inside the target repo (default: cwd)")
    p.add_argument(
        "--force",
        action="store_true",
        help="take over a core.hooksPath that points at another hook manager",
    )
    p.add_argument("--rev", help="pre-commit mode: pin this rev instead of resolving one")
    p.add_argument(
        "--repo-url",
        default=REPO_URL,
        help="pre-commit mode: repository URL to reference (default: the GitHub repo)",
    )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="install.py",
        description="Install git-hooks-collection into a repository.",
    )
    add_install_arguments(p)
    p.add_argument("--uninstall", action="store_true", help="remove the native installation")
    return p


def run_install(args: argparse.Namespace) -> int:
    target = Path(args.target).resolve()
    root = git_root(target)
    if root is None:
        fail(f"{target} is not inside a git repository (run 'git init' first)")
        return EXIT_USAGE

    if getattr(args, "uninstall", False):
        return uninstall(root)

    info(f"target repository: {root}")
    if args.mode == "pre-commit":
        selected = resolve_selection(args, config_exists=False) or list(ALL_NAMES)
        if not selected:
            fail("no hooks selected; nothing to do")
            return EXIT_FAIL
        return install_pre_commit(root, selected, rev=args.rev, repo_url=args.repo_url)

    selected = resolve_selection(args, config_exists=(root / ".githooks.yaml").exists())
    if selected is not None and not selected:
        fail("no hooks selected; nothing to do")
        return EXIT_FAIL
    return install_native(root, selected, force=args.force)


def main(argv: Optional[List[str]] = None) -> int:
    return run_install(build_parser().parse_args(argv))
