"""`githooks doctor` on healthy and deliberately broken repositories."""

from __future__ import annotations

import subprocess
import sys

import pytest
from _helpers import ROOT, git, write
from _repo import install

CLI = [sys.executable, "-m", "pre_commit_hooks"]


def doctor(path):
    proc = subprocess.run(
        [*CLI, "doctor"],
        cwd=str(path),
        capture_output=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    return proc.returncode, proc.stdout + proc.stderr


@pytest.fixture
def installed(tmp_path, git_env):
    path = tmp_path / "doc"
    path.mkdir()
    git(path, "init", "-q", "-b", "main")
    assert install(path, "--all").rc == 0
    return path


def _edit_config(path, old, new):
    cfg = path / ".githooks.yaml"
    text = cfg.read_text(encoding="utf-8")
    assert old in text
    write(cfg, text.replace(old, new))


def test_clean_install_passes(installed):
    rc, out = doctor(installed)
    assert rc == 0, out
    assert "core.hooksPath = .githooks" in out
    assert "the wrappers run " in out  # a wrapper was really executed
    assert "vendored copy matches" in out
    assert "0 error(s)" in out or "no problems found" in out


def test_typo_in_check_name(installed):
    _edit_config(installed, "    - secrets\n", "    - secret\n")
    rc, out = doctor(installed)
    assert rc == 1
    assert "unknown check 'secret' (did you mean 'secrets'?)" in out


def test_typo_in_setting(installed):
    _edit_config(installed, "  max_bytes: 5242880", "  max_byte: 5242880")
    rc, out = doctor(installed)
    assert rc == 1
    assert "large_files.max_byte: unknown setting (did you mean 'max_bytes'?)" in out


def test_missing_wrapper(installed):
    (installed / ".githooks" / "commit-msg").unlink()
    rc, out = doctor(installed)
    assert rc == 1
    assert "conventional-commit enabled, but .githooks/commit-msg is missing" in out


def test_foreign_hooks_path(installed):
    git(installed, "config", "core.hooksPath", ".husky")
    rc, out = doctor(installed)
    assert rc == 1
    assert "core.hooksPath points at '.husky'" in out


def test_unset_hooks_path(installed):
    git(installed, "config", "--unset", "core.hooksPath")
    rc, out = doctor(installed)
    assert rc == 1
    assert "core.hooksPath is not set" in out


@pytest.mark.skipif(__import__("importlib").util.find_spec("yaml") is None, reason="needs PyYAML")
def test_parser_divergence(installed):
    _edit_config(installed, '    - "wip:"', "    - wip:")
    rc, out = doctor(installed)
    assert rc == 1
    assert "PyYAML and the bundled parser disagree at no_fixup.block_patterns[4]" in out


def test_prefix_mode_that_conventional_commit_would_reject(installed):
    _edit_config(installed, "  mode: trailer", "  mode: prefix")
    _edit_config(installed, "  template: '[{issue}] '", "  template: '{issue}: '")
    rc, out = doctor(installed)
    assert rc == 1
    assert "which conventional-commit rejects" in out


def test_drift_between_vendored_copy_and_this_version(installed):
    init = installed / ".githooks" / "pre_commit_hooks" / "__init__.py"
    write(init, init.read_text(encoding="utf-8").replace('__version__ = "', '__version__ = "0.0.'))
    rc, out = doctor(installed)
    assert rc == 0  # a warning, not an error
    assert "vendored copy is 0.0." in out


def test_not_installed(tmp_path, git_env):
    path = tmp_path / "bare"
    path.mkdir()
    git(path, "init", "-q")
    rc, out = doctor(path)
    assert rc == 1
    assert "git-hooks-collection is not installed here" in out


def test_framework_mode_missing_hook_types(tmp_path, git_env):
    path = tmp_path / "fw"
    path.mkdir()
    git(path, "init", "-q")
    write(
        path / ".pre-commit-config.yaml",
        "repos:\n  - repo: https://github.com/AleBrito124356/git-hooks-collection\n"
        "    rev: v0.1.0\n    hooks:\n      - id: githooks-secrets\n"
        "      - id: githooks-conventional-commit\n",
    )
    write(path / ".git" / "hooks" / "pre-commit", "#!/bin/sh\n# File generated by pre-commit\n")
    rc, out = doctor(path)
    assert rc == 1
    assert "pre-commit: pre-commit hook installed (secrets)" in out
    assert (
        "commit-msg hook type is not installed. Fix: pre-commit install --hook-type commit-msg"
        in out
    )
    assert "rev v0.1.0 was never released" in out


def test_pinned_rev_resolves_in_the_source_repository(tmp_path, git_env):
    path = tmp_path / "pc"
    path.mkdir()
    git(path, "init", "-q")
    result = install(path, "--mode", "pre-commit", "--hooks", "secrets", "--repo-url", str(ROOT))
    assert result.rc == 0, result.out
    text = (path / ".pre-commit-config.yaml").read_text(encoding="utf-8")
    rev = text.split("rev:", 1)[1].split()[0]
    assert git(ROOT, "cat-file", "-e", f"{rev}^{{commit}}", check=False).returncode == 0
    assert f"repo: {ROOT}" in text
